#!/bin/bash

export MESSAGE=$(<$1)
export JIRA_ISSUE_TAG="SUIC-[0-9]+[[:space:]]+[a-z]+"

if [[ $MESSAGE =~ $JIRA_ISSUE_TAG ]]; then
echo -e “Great, your commit message contains a JIRA issue!”
exit 0;
fi

echo -e “You forgot to add a JIRA issue number!”;
exit 1;